### ISSUE TITLE
Unable to run as per steps in readme

### ISSUE THREAD

**Issue by shivbuddhaatcapgemini** [fusionfabric/finastra-nodejs-libs#21]
i have installed the latest node js , and followed the steps a) npm install and  b) npm run start getting the following error 

Please help 

[Nest] 11424   - 05/20/2020, 12:43:04 AM   [NestFactory] Starting Nest application...
[Nest] 11424   - 05/20/2020, 12:43:04 AM   [InstanceLoader] AppModule dependencies initialized +26ms
[Nest] 11424   - 05/20/2020, 12:43:04 AM   [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 11424   - 05/20/2020, 12:43:04 AM   [InstanceLoader] PassportModule dependencies initialized +1ms
[Nest] 11424   - 05/20/2020, 12:43:04 AM   [InstanceLoader] JwtModule dependencies initialized +1ms
[Nest] 11424   - 05/20/2020, 12:43:04 AM   [InstanceLoader] ConfigHostModule dependencies initialized +1ms
[Nest] 11424   - 05/20/2020, 12:43:04 AM   [InstanceLoader] CorporateAccountsModule dependencies initialized +1ms
[Nest] 11424   - 05/20/2020, 12:43:04 AM   [InstanceLoader] CatsModule dependencies initialized +1ms
[Nest] 11424   - 05/20/2020, 12:43:04 AM   [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 11424   - 05/20/2020, 12:43:04 AM   [InstanceLoader] GraphQLSchemaBuilderModule dependencies initialized +7ms
[Nest] 11424   - 05/20/2020, 12:43:04 AM   [ExceptionHandler] The "url" argument must be of type string. Received undefined +1ms
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:117:11)
    at Url.parse (url.js:159:3)
    at Object.urlParse [as parse] (url.js:154:13)
    at Function.discover (D:\WS3\finastranodejs\node_modules\openid-client\lib\issuer.js:212:24)
    at InstanceWrapper.useFactory [as metatype] (D:\WS3\finastranodejs\dist\libs\oidc\src\oidc.module.js:31:58)
    at Injector.instantiateClass (D:\WS3\finastranodejs\node_modules\@nestjs\core\injector\injector.js:292:55)
    at callback (D:\WS3\finastranodejs\node_modules\@nestjs\core\injector\injector.js:76:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Injector.resolveConstructorParams (D:\WS3\finastranodejs\node_modules\@nestjs\core\injector\injector.js:117:24)
    at async Injector.loadInstance (D:\WS3\finastranodejs\node_modules\@nestjs\core\injector\injector.js:80:9)

**Comment by bcldvd** [comment]
Hi, you need to specify required values as env variables !
Create a .env file for more convenience at dev time ;)
